
# Server properties
server:
  port: 5001


# Database and other additional properties required for configuring as a microservice
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cognizant_fse
    username: root
    password: pass@word1
  application:
    name: COMPANY-SERVICE

# Hibernate properties
  jpa:
    how-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect


# Eureka client properties
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    hostname: localhost